name: Update Subscription

on:
  schedule:
    - cron: '0 23 * * *'  # 每天UTC时间23点，即北京时间早上7点
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up git configuration
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update subscription file
        run: |
          curl -s -L "https://rss.main.hitun.io/link/sQrHTGf1JdLgJKoS?mu=1" > subscribe.txt
          if [ -s subscribe.txt ]; then
            echo "Subscription updated successfully."
          else
            echo "Failed to fetch subscription." && exit 1
          fi

      
