name: Update Subscription

on:
  schedule:
    - cron: '0 3 * * *' # 每天UTC时间3点
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up git configuration
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update subscription file
        run: |
          curl -s -L "https://rss.main.hitun.io/link/sQrHTGf1JdLgJKoS?mu=1" > subscribe.txt
          if [ -s subscribe.txt ]; then
            echo "Subscription updated successfully."
          else
            echo "Failed to fetch subscription." && exit 1
          fi

      - name: Commit and push if changed
        run: |
          git add subscribe.txt
          timestamp=$(date -u)
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update subscription at ${timestamp}"
            git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" main
          fi
